export const projectData = [
  {
    title: "Personal Portfolio Website",
    slug: "personal-portfolio-website",
    status: "PUBLISHED",
    category: "Web Development",
    description:
      "A modern personal portfolio built with Next.js, Tailwind CSS, and TypeScript. It includes a blog, project showcase, and contact form. The site is fully responsive, optimized for SEO, and integrates with GitHub API to display real-time repositories. Designed for showcasing professional experience and creative work in a clean and minimal interface.",
    thumb: "/images/projects/portfolio.png",
    liveUrl: "https://portfolio.example.com",
    repoUrl: "https://github.com/user/portfolio",
    startDate: "2024-01-10T00:00:00.000Z",
    endDate: "2024-02-05T00:00:00.000Z",
  },
  {
    title: "E-commerce Platform",
    slug: "ecommerce-platform",
    status: "PUBLISHED",
    category: "E-commerce",
    description:
      "A scalable full-stack e-commerce solution featuring product management, cart, checkout, and order tracking. Built with Next.js, Prisma, PostgreSQL, and Stripe for payments. Includes admin dashboards, dynamic product filters, and role-based authentication for customers and admins. SEO-optimized with fast loading pages for improved conversions.",
    thumb: "/images/projects/ecommerce.png",
    liveUrl: "https://shop.example.com",
    repoUrl: "https://github.com/user/ecommerce",
    startDate: "2024-02-15T00:00:00.000Z",
    endDate: "2024-04-01T00:00:00.000Z",
  },
  {
    title: "Project Management Dashboard",
    slug: "project-management-dashboard",
    status: "PUBLISHED",
    category: "SaaS",
    description:
      "A project management tool inspired by Trello and Asana. It allows users to create boards, manage tasks, assign team members, and track progress with drag-and-drop UI. Built with React, NestJS, and PostgreSQL. Supports real-time collaboration with WebSockets and offers analytics with charts for project tracking.",
    thumb: "/images/projects/pm-dashboard.png",
    liveUrl: "https://pm.example.com",
    repoUrl: "https://github.com/user/pm-dashboard",
    startDate: "2024-03-01T00:00:00.000Z",
    endDate: "2024-05-15T00:00:00.000Z",
  },
  {
    title: "AI Content Generator",
    slug: "ai-content-generator",
    status: "DRAFT",
    category: "AI",
    description:
      "An AI-powered platform that generates blog posts, social media captions, and SEO-friendly content. Integrates OpenAI API with fine-tuned prompts for high-quality writing. Users can save drafts, export as Markdown, and organize projects. Built with Next.js, TypeScript, and Tailwind CSS for sleek UI.",
    thumb: "/images/projects/ai-generator.png",
    liveUrl: "https://aigen.example.com",
    repoUrl: "https://github.com/user/ai-generator",
    startDate: "2024-04-20T00:00:00.000Z",
    endDate: "2024-06-10T00:00:00.000Z",
  },
  {
    title: "Learning Management System",
    slug: "learning-management-system",
    status: "PUBLISHED",
    category: "Education",
    description:
      "A full-featured LMS for online courses, quizzes, and student progress tracking. Features include video streaming, certification, and teacher dashboards. Built with Next.js, NestJS, and PostgreSQL. Payment integration allows monetization of courses, while students enjoy a gamified learning experience with badges and leaderboards.",
    thumb: "/images/projects/lms.png",
    liveUrl: "https://lms.example.com",
    repoUrl: "https://github.com/user/lms",
    startDate: "2024-05-01T00:00:00.000Z",
    endDate: "2024-07-30T00:00:00.000Z",
  },
  {
    title: "Job Board Platform",
    slug: "job-board-platform",
    status: "PUBLISHED",
    category: "Recruitment",
    description:
      "A job portal with employer and job seeker dashboards. Employers can post jobs, manage applicants, and schedule interviews. Job seekers can build profiles, upload resumes, and track applications. Built with Next.js, Prisma, and PostgreSQL. Includes advanced search and filtering for jobs by location, skills, and salary range.",
    thumb: "/images/projects/job-board.png",
    liveUrl: "https://jobs.example.com",
    repoUrl: "https://github.com/user/job-board",
    startDate: "2024-06-10T00:00:00.000Z",
    endDate: "2024-08-01T00:00:00.000Z",
  },
  {
    title: "Fitness Tracking App",
    slug: "fitness-tracking-app",
    status: "DRAFT",
    category: "Health & Fitness",
    description:
      "A web-based fitness tracker for workouts, meal logging, and progress charts. Includes integration with wearable devices like Fitbit and Apple Watch. Built with Next.js, GraphQL, and MongoDB. Features include personalized workout recommendations, progress insights, and social features for accountability groups.",
    thumb: "/images/projects/fitness.png",
    liveUrl: "https://fittrack.example.com",
    repoUrl: "https://github.com/user/fitness-tracker",
    startDate: "2024-07-01T00:00:00.000Z",
    endDate: "2024-08-25T00:00:00.000Z",
  },
  {
    title: "Crypto Portfolio Manager",
    slug: "crypto-portfolio-manager",
    status: "PUBLISHED",
    category: "Finance",
    description:
      "A dashboard for tracking cryptocurrency investments. Fetches real-time data from CoinGecko API. Users can add wallets, track portfolio growth, and generate reports. Built with Next.js, Node.js, and MongoDB. Includes charts, alerts, and a dark/light mode toggle for better UX.",
    thumb: "/images/projects/crypto.png",
    liveUrl: "https://crypto.example.com",
    repoUrl: "https://github.com/user/crypto-portfolio",
    startDate: "2024-08-05T00:00:00.000Z",
    endDate: "2024-09-20T00:00:00.000Z",
  },
  {
    title: "Real Estate Listing Platform",
    slug: "real-estate-listing-platform",
    status: "PUBLISHED",
    category: "Real Estate",
    description:
      "A platform for real estate agents and buyers. Features advanced property search, map integration, mortgage calculator, and virtual tours. Built with Next.js, Leaflet, and PostgreSQL. Includes admin dashboard for agents to manage listings and AI recommendations for buyers.",
    thumb: "/images/projects/real-estate.png",
    liveUrl: "https://realestate.example.com",
    repoUrl: "https://github.com/user/real-estate",
    startDate: "2024-09-01T00:00:00.000Z",
    endDate: "2024-10-15T00:00:00.000Z",
  },
  {
    title: "SaaS Billing System",
    slug: "saas-billing-system",
    status: "PUBLISHED",
    category: "SaaS",
    description:
      "A subscription billing platform for SaaS businesses. Handles customer subscriptions, payments, and invoices. Integrates with Stripe for payments and supports multiple pricing models. Built with Next.js, NestJS, and PostgreSQL. Includes admin reports, churn analytics, and role-based access for finance teams.",
    thumb: "/images/projects/billing.png",
    liveUrl: "https://billing.example.com",
    repoUrl: "https://github.com/user/saas-billing",
    startDate: "2024-10-05T00:00:00.000Z",
    endDate: "2024-11-20T00:00:00.000Z",
  },
];
